name: heart
description: "Heart of Yours API"
version: 1.0.0
repository: "https://github.com/kit-g/heart-api.git"
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  relic: ^0.14.0
  openid_client: ^0.4.9+2
  heart_models:
    git:
      url: "https://github.com/kit-g/heart-of-yours.git"
      ref: "main"
      path: "shared/heart_models"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  analyzer: ^9.0.0
