name: heart
description: "Heart of Yours API"
version: 1.0.0
repository: "https://github.com/kit-g/heart-api.git"
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  aws_client: ^0.7.1
  heart_models:
    git:
      url: "https://github.com/kit-g/heart-of-yours.git"
      ref: "main"
      path: "shared/heart_models"
  logging: ^1.3.0
  openid_client: ^0.4.9+2
  relic: ^0.14.0
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  mockito: ^5.6.1
  test: ^1.25.6

