name: "Deploy Dart API"

on:
  push:
    branches: [ main, new-app ]
#    paths:
#      - 'api_v2/**'
#      - '.github/workflows/deploy-v2.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "ca-central-1"
  AWS_ROLE: "arn:aws:iam::583168578067:role/HeartGitHubActionsDeployRole"
  FUNCTION_NAME: "heart-api-v2"
  API: "https://bsm50dxdal.execute-api.ca-central-1.amazonaws.com/api/v2"

jobs:
  lint:
    name: "Lint Dart Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: "Install dependencies"
        working-directory: api_v2
        run: dart pub get
      - name: "Run Analysis"
        working-directory: api_v2
        run: dart analyze

  build-and-deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v3

      - name: "Export commit SHA"
        id: commit
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - uses: dart-lang/setup-dart@v1

      - name: "Build Lambda binary"
        working-directory: api_v2
        run: |
          dart pub get
          COMMIT=${{ steps.commit.outputs.commit }} ARTIFACTS_DIR=. make build-ApiV2Function
          zip function.zip bootstrap

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Update Lambda Function Code"
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://api_v2/function.zip \
            --region ${{ env.AWS_REGION }} > /dev/null

    outputs:
      commit: ${{ steps.save-commit.outputs.sha }}

  smoke-test:
    name: "Smoke Test"
    runs-on: ubuntu-latest
    needs: [ build-and-deploy ]
    env:
      EXPECTED_COMMIT: ${{ needs.build-and-deploy.outputs.commit }}
    steps:
      - name: "Check /charts endpoint"
        run: |
          echo "Expecting commit: $EXPECTED_COMMIT"
          
          response=$(curl -s $API/version)
          echo "Response: $response"
          
          deployed_commit=$(echo "$response" | jq -r .commit)
          
          if [ "$deployed_commit" != "$EXPECTED_COMMIT" ]; then
              echo "Deployed commit ($deployed_commit) does not match expected ($EXPECTED_COMMIT)"
              exit 1
          fi
          
          echo "Smoke test passed: commit matches."